#ifndef LIBYAML_CONFIG_H
#define LIBYAML_CONFIG_H

#define YAML_VERSION_MAJOR  0
#define YAML_VERSION_MINOR  2
#define YAML_VERSION_PATCH  5
#define YAML_VERSION_STRING "0.2.5"

#define HAVE_CONFIG_H 1

#endif
