#!/usr/bin/env python3
"""
Extract user-facing string literals from a C source file.

Walks every `write_user(...)`, `vwrite_user(...)`, `write_room*(...)`,
and `vwrite_level*(...)` invocation and prints a YAML stub of catalog
keys with the literal value. Run before converting a command file:

    python tools/locale/extract.py src/commands/foo.c > foo.yml

Then paste the stub into files/langs/en_GB/strings.yml, edit keys,
and convert the C source.
"""
import argparse
import os
import re
import sys

OUTPUT_FNS = re.compile(r"\b(v?write_user|v?write_room(?:_except)?|v?write_level|v?write_monitor)\s*\(")
LITERAL = re.compile(r'"((?:\\.|[^"\\])*)"')


def suggest_key(filename, literal, index):
    base = os.path.splitext(os.path.basename(filename))[0]
    visible = re.sub(r"~[A-Za-z0-9]{2}", "", literal)
    visible = re.sub(r"[^A-Za-z0-9]+", "_", visible).strip("_").lower()
    if not visible:
        visible = "msg"
    visible = "_".join(visible.split("_")[:4])
    return f"{base}.{visible or f'msg_{index}'}"


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("source", help="C source file")
    args = p.parse_args()

    with open(args.source, encoding="utf-8", errors="replace") as f:
        text = f.read()

    findings = []
    for m in OUTPUT_FNS.finditer(text):
        i = m.end()
        depth = 1
        snippet = []
        while i < len(text) and depth > 0:
            c = text[i]
            if c == "(":
                depth += 1
            elif c == ")":
                depth -= 1
                if depth == 0:
                    break
            elif c == ";" and depth == 0:
                break
            snippet.append(c)
            i += 1
        snippet_text = "".join(snippet)
        lits = LITERAL.findall(snippet_text)
        if not lits:
            continue
        findings.append((m.start(), lits[0]))

    print(f"# Stub for {args.source} - review keys before pasting.")
    print(f"# Generated by tools/locale/extract.py.")
    for idx, (offset, lit) in enumerate(findings, start=1):
        line_no = text.count("\n", 0, offset) + 1
        key = suggest_key(args.source, lit, idx)
        yaml_val = lit.replace("\\", "\\\\").replace('"', '\\"')
        print(f"\n# {args.source}:{line_no}")
        print(f'{key}: "{yaml_val}"')


if __name__ == "__main__":
    sys.exit(main())
