version       0.3
password      NUqf0BPO/85EI
promote_date  on Thursday 2nd August 2001 at 10:00pm
times         995755517 146 7620 995747897
levels        2 2 0 0 0
general       -1 0 0 0 1 0 0 0
user_set      0 0 0 23 1 1 0 0 0 0 1 0 #UNSET 0
user_ignores  0 0 0 0 0 0 0 0
purging       1
last_site     127.0.0.1 (no
mail_verify   #UNSET
description   is a newbie needing a desc.
in_phrase     wanders in.
out_phrase    wanders out
email         #UNSET
homepage      #UNSET
recap_name    Identduser
games         0 0 0 0 6 10 1000 3000
